// This file Copyright © Transmission authors and contributors.
// It may be used under the MIT (SPDX: MIT) license.
// License text can be found in the licenses/ folder.

#pragma once

#include <AvailabilityMacros.h>

#ifndef TR_MACOS_SDK_BEFORE_10_5
#define TR_MACOS_SDK_BEFORE_10_5 (MAC_OS_X_VERSION_MAX_ALLOWED < 1050)
#endif

#ifndef TR_MACOS_SDK_BEFORE_10_6
#define TR_MACOS_SDK_BEFORE_10_6 (MAC_OS_X_VERSION_MAX_ALLOWED < 1060)
#endif

#ifndef TR_MACOS_SDK_BEFORE_10_7
#define TR_MACOS_SDK_BEFORE_10_7 (MAC_OS_X_VERSION_MAX_ALLOWED < 1070)
#endif

#ifndef TR_MACOS_SDK_BEFORE_10_8
#define TR_MACOS_SDK_BEFORE_10_8 (MAC_OS_X_VERSION_MAX_ALLOWED < 1080)
#endif

#ifndef TR_MACOS_SDK_BEFORE_10_9
#define TR_MACOS_SDK_BEFORE_10_9 (MAC_OS_X_VERSION_MAX_ALLOWED < 1090)
#endif

#ifndef TR_MACOS_SDK_BEFORE_10_10
#define TR_MACOS_SDK_BEFORE_10_10 (MAC_OS_X_VERSION_MAX_ALLOWED < 101000)
#endif

#ifndef TR_MACOS_SDK_BEFORE_10_11
#define TR_MACOS_SDK_BEFORE_10_11 (MAC_OS_X_VERSION_MAX_ALLOWED < 101100)
#endif

#ifndef TR_MACOS_SDK_BEFORE_10_12
#define TR_MACOS_SDK_BEFORE_10_12 (MAC_OS_X_VERSION_MAX_ALLOWED < 101200)
#endif

#ifndef TR_MACOS_SDK_BEFORE_10_13
#define TR_MACOS_SDK_BEFORE_10_13 (MAC_OS_X_VERSION_MAX_ALLOWED < 101300)
#endif

#ifndef TR_MACOS_SDK_BEFORE_10_14
#define TR_MACOS_SDK_BEFORE_10_14 (MAC_OS_X_VERSION_MAX_ALLOWED < 101400)
#endif

#ifndef TR_MACOS_SDK_BEFORE_10_15
#define TR_MACOS_SDK_BEFORE_10_15 (MAC_OS_X_VERSION_MAX_ALLOWED < 101500)
#endif

#ifndef TR_MACOS_SDK_BEFORE_11_0
#define TR_MACOS_SDK_BEFORE_11_0 (MAC_OS_X_VERSION_MAX_ALLOWED < 110000)
#endif

#ifndef TR_MACOS_SDK_BEFORE_12_0
#define TR_MACOS_SDK_BEFORE_12_0 (MAC_OS_X_VERSION_MAX_ALLOWED < 120000)
#endif

#ifndef TR_MACOS_DEPLOYMENT_BEFORE_10_5
#define TR_MACOS_DEPLOYMENT_BEFORE_10_5 (MAC_OS_X_VERSION_MIN_REQUIRED < 1050)
#endif

#ifndef TR_MACOS_DEPLOYMENT_BEFORE_10_6
#define TR_MACOS_DEPLOYMENT_BEFORE_10_6 (MAC_OS_X_VERSION_MIN_REQUIRED < 1060)
#endif

#ifndef TR_MACOS_DEPLOYMENT_BEFORE_10_7
#define TR_MACOS_DEPLOYMENT_BEFORE_10_7 (MAC_OS_X_VERSION_MIN_REQUIRED < 1070)
#endif

#ifndef TR_MACOS_DEPLOYMENT_BEFORE_10_8
#define TR_MACOS_DEPLOYMENT_BEFORE_10_8 (MAC_OS_X_VERSION_MIN_REQUIRED < 1080)
#endif

#ifndef TR_MACOS_DEPLOYMENT_BEFORE_10_9
#define TR_MACOS_DEPLOYMENT_BEFORE_10_9 (MAC_OS_X_VERSION_MIN_REQUIRED < 1090)
#endif

#ifndef TR_MACOS_DEPLOYMENT_BEFORE_10_10
#define TR_MACOS_DEPLOYMENT_BEFORE_10_10 (MAC_OS_X_VERSION_MIN_REQUIRED < 101000)
#endif

#ifndef TR_MACOS_DEPLOYMENT_BEFORE_10_11
#define TR_MACOS_DEPLOYMENT_BEFORE_10_11 (MAC_OS_X_VERSION_MIN_REQUIRED < 101100)
#endif

#ifndef TR_MACOS_DEPLOYMENT_BEFORE_10_12
#define TR_MACOS_DEPLOYMENT_BEFORE_10_12 (MAC_OS_X_VERSION_MIN_REQUIRED < 101200)
#endif

#ifndef TR_MACOS_DEPLOYMENT_BEFORE_10_13
#define TR_MACOS_DEPLOYMENT_BEFORE_10_13 (MAC_OS_X_VERSION_MIN_REQUIRED < 101300)
#endif

#ifndef TR_MACOS_DEPLOYMENT_BEFORE_10_14
#define TR_MACOS_DEPLOYMENT_BEFORE_10_14 (MAC_OS_X_VERSION_MIN_REQUIRED < 101400)
#endif

#ifndef TR_MACOS_DEPLOYMENT_BEFORE_10_15
#define TR_MACOS_DEPLOYMENT_BEFORE_10_15 (MAC_OS_X_VERSION_MIN_REQUIRED < 101500)
#endif

#ifndef TR_MACOS_DEPLOYMENT_BEFORE_11_0
#define TR_MACOS_DEPLOYMENT_BEFORE_11_0 (MAC_OS_X_VERSION_MIN_REQUIRED < 110000)
#endif

#ifndef TR_MACOS_DEPLOYMENT_BEFORE_12_0
#define TR_MACOS_DEPLOYMENT_BEFORE_12_0 (MAC_OS_X_VERSION_MIN_REQUIRED < 120000)
#endif
